### ISSUE TITLE
dbgap_subject_id should have integer type

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/primed_data_models#6]
In the subject table, subject_id should be the dbgap SUBJECT_ID column for dbgap studies. dbgap_subject_id should be the identifier of the same name added to studies by the dbgap curators and used to identify cross-study duplicates. This value is always an integer.

**Comment by smgogarten** [comment]
On second thought, recording this as integer can lead to inappropriate usage. Examples are displaying numbers without leading zeros or with ".0" appended. Perhaps identifiers should always be strings.

**Comment by mconomos** [comment]
@smgogarten -- that's a good point. Keeping them as strings makes sense to me. If we wanted some sort of check, are the dbgap SUBJECT_IDs always the same number of characters?
